### ISSUE TITLE
ip6tables.lua conflicts with luci-app-statistics

### ISSUE THREAD

**Issue by Atticus-** [oofnikj/iptmon#1]
Now that `luci-app-statistics` has merged [your PR](https://github.com/openwrt/luci/pull/3763), attempting to install via the current release gives the following error:

```
root@OpenWrt:/tmp# opkg install iptmon_0.0.2-1_all.ipk
Installing iptmon (0.0.2-1) to root...
Collected errors:
 * check_data_file_clashes: Package iptmon wants to install file /usr/lib/lua/luci/statistics/rrdtool/definitions/ip6tables.lua
	But that file is already provided by package  * luci-app-statistics
 * opkg_install_cmd: Cannot install package iptmon.
```

We should remove that patch and update the README, perhaps with a note for users to update `luci-app-statistics` if IPv6 doesn't work for them.

**Comment by oofnikj** [comment]
Thanks for pointing that out! I will publish a new release and add your suggestions to the readme shortly.
