### ISSUE TITLE
rx_bin & tx_bin entries

### ISSUE THREAD

**Issue by kwirsch7** [oofnikj/iptmon#4]
I installed iptmon_0.0.5-1_all.ipk on a router running OpenWRT 19.07.3, dnsmasq 2.80-16.1. Everything is working well but there are unexplained entries for rx_bin & tx_bin showing up. I don't have any devices called "bin", I checked on the router and there is nothing with that name or an associated IP-address. I wonder if there may be some corner case where dnsmasq calls iptmon when no IP-address is being assigned.

**Comment by oofnikj** [comment]
Hi @kwirsch7, thanks for opening an issue. 
I experienced this same thing a couple times during development but the problem went away after a couple iterations. I'll have a look at it over the weekend and update.

**Comment by oofnikj** [comment]
I've monitored a fresh installation for several days and noticed that the `rx_bin` and `tx_bin` files show up right on init, but if they are removed, they don't come back. There is also no record of these entries in `iptables`.

I resorted to just running 
```
# find /tmp/rrd -regex ".*[tr]x_bin.rrd" -exec rm {} \;
```
to get rid of them. Seems to have done the trick.

I can't seem to figure out where they are coming from.

**Comment by oofnikj** [comment]
Haven't seen this issue re-appear in some time, closing for now. Will re-open if needed.

**Comment by darrepac** [comment]
Here is what I have in mine... it sounds like a path....
obviously I have no device with that name
![image](https://user-images.githubusercontent.com/7128994/109558245-6f603500-7ad9-11eb-91d9-3776b2d64e56.png)

**Comment by kwirsch7** [comment]
I just checked with version 0.1.6 and see this as well.
![20210301_iptmonScreenshot](https://user-images.githubusercontent.com/50776796/109561426-242f2d80-7aab-11eb-8e9f-691a2b43b969.png)
. This is with OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.044.30835-34e0d65

**Comment by oofnikj** [comment]
Super weird. @kwirsch7 what platform are you running on? 
Does the phantom host appear in the output of `iptables -t mangle -nvL`?

If you manually delete the oddly named RRD records, does the problem re-appear?
This can be accomplished with a slightly modified version of the command above:
```sh
# find /tmp/rrd -regex ".*[tr]x_bin.*\.rrd" -exec rm {} \;
```

**Comment by kwirsch7** [comment]
Hi @oofnikj 

this is on a Netgear Nighthawk X4S R7800 Wifi router (ARMv7 Processor rev 0 (v7l)).
Interestingly the phantom host does not appear in the output of `iptables -t mang\le -nvL`.

I've removed the oddly named RRD records per your recommendation and will send an update later today to let you know if they reappear (so far they haven't). Interestingly before removing I looked at the file modification dates for these and it seems to coincide with the last time the router was rebooted and had not been updated since. I'll also try reloading the router at a convenient time to check if that makes a difference and report back. Thanks!

**Comment by darrepac** [comment]
I gave it a try: I rebooted and... the strange did not appear

**Comment by kwirsch7** [comment]
After rebooting the router the phantom entry has not reappeared.

**Comment by darrepac** [comment]
After, he is back!
![image](https://user-images.githubusercontent.com/7128994/109710670-405fc700-7b9e-11eb-9c3e-33faa5fe24ae.png)

**Comment by kwirsch7** [comment]
I did one more reboot and the phantom entry has not returned.

I have one other interesting thing where for most but not all devices a duplicate entry with just the device name and a second one with ".lan" added is present. I will do some more debugging as I suspect that may be due to my config and if necessary open another issue report.

**Comment by darrepac** [comment]
All my devices are with .lan ... may-be they are the ones that have static ip??

**Comment by alexwbaule** [comment]
Is in the IPV6 entry that is created that.

     182    39558 RETURN     all      *      *       ::/0                 xxxx:14c:110:b82f:5fd:xxxx:xxxx:xxxx  /* tx_bindevetclibmntoverlayprocromrootsbinsystmpusrvarwww */

**Comment by alexwbaule** [comment]
I found the error that produces this kind of entry, i will do a PR.
