### ISSUE TITLE
problem with second WiFi network

### ISSUE THREAD

**Issue by zyzakin** [oofnikj/iptmon#5]
during installation I saw that the script has a problem with an additional WiFi network

> 
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: no lease, failing
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: no lease, failing
udhcpc: started, v1.30.1
udhcpc: sending discover
udhcpc: no lease, failing
Warning: Section @zone[0] (lan) cannot resolve device of network 'IOT'
Warning: Option @redirect[0].dst is unknown
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 mangle table
 * Flushing conntrack table ...
>

I don't know if it reads the error message correctly, but it may need to be repaired

**Comment by oofnikj** [comment]
Hi @zyzakin, can you please share your full `/etc/config/dhcp` file? I hope it will provide enough information to help debug the issue.
